### ISSUE TITLE
ERROR / EXCEPTION when scanning series without overview (e.g. #273716 with lang setting German)

### ISSUE THREAD

**Issue by F1zye** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#15]
Scanning https://thetvdb.com/series/273716-show resulted in the error shown in the linked log
https://paste.kodi.tv/luyafulura.kodi

Error was "fixed" by adding overview

**Comment by popcornmix** [comment]
I'm getting same exception. Log: http://ix.io/49DS

If I visit the url (https://api4.thetvdb.com/v4/episodes/4098848/translations/eng) it's attempting to fetch in browser I see:
```
message | "Unauthorized"
```
I'm seeing this with Battlestar Galacticta (2003) and This Life.

**Comment by antheaezzell** [comment]
Ticketed for internal investigation - https://mediamorph.atlassian.net/browse/TVD-3390

**Comment by antheaezzell** [comment]
@F1zye a fix should have been released in 1.1.2. Please let me know if the issue persists.
