### ISSUE TITLE
metadata for wrong show is pulled

### ISSUE THREAD

**Issue by lainestump** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#28]
For a directory named "The Tick (2016)" with files named "Season 01/The.Tick.2016.S01Exx.blah.mkv", etc, the v4 scraper is deciding that the files are all episodes of "You Can't Cuck the Tuck (2016)" instead. I have triple checked, and there are no misspellings.

**Comment by antheaezzell** [comment]
Hi. Apologies on getting back tot his later. Can you please provide a bug log @lainestump

**Comment by lainestump** [comment]
Hi!  Whatever was causing the issue, I just setup a couple of new KODI systems using the TVDBv4 scraper, and this mistaken ID is no longer made - the correct show is now detected. So it has been magically fixed :-)
