### ISSUE TITLE
Episodes are scraping as TBA on plugin when site is updated

### ISSUE THREAD

**Issue by antheaezzell** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#37]
Kodi user is reporting in [osTicket](https://support.thetvdb.com/scp/tickets.php?id=21554) that they're using Kodi 20.1 with the official TheTVDB v4 scraper and are unable to scrape season 2 of the show [Human Resources.](https://thetvdb.com/series/human-resources-2021) All the information is correctly filled in on TVDB (https://thetvdb.com/series/human-resources-2021/seasons/official/2) but no information is being scraped. All the episodes in Kodi end up being named TBA.

User is using all the standard settings, language, season type, but it's not working. Season 1 scrapes fine. User thought it might be a caching problem, so they waited and retried, but it's been half a week now since the information has been on the website and it still isn't getting scraped.

Bug log provided below:

[kodi.log](https://github.com/thetvdb/metadata.tvshows.thetvdb.com.v4.python/files/11773157/kodi.log)

Ticket: https://support.thetvdb.com/scp/tickets.php?id=21554

**Comment by antheaezzell** [comment]
Looking into this.

Internal ticket for our reference: https://whipmedia.atlassian.net/browse/TVD-3773

**Comment by Nopel2020** [comment]
Hi, I am the Kodi user that opened the ticket. FYI, the exact same thing is happening with the latest episodes of Project Runway, S20E01 ('TBA') and S20E02 (is scraped as 'Episode 2'). Both episodes have their full titles and all info set correctly on thetvdb.com. It seems like the API is scraping obsolete info. New episodes of other shows are being scraped correctly though.

**Comment by maxifwortman** [comment]
Hi @Nopel2020, I see the correct info in the api calls https://api4.thetvdb.com/v4/episodes/303131/extended and 'https://api4.thetvdb.com/v4/episodes/302507/extended for the episodes you are describing. So, I think the problem is not caused by the api call. Could it be a different problem, like with the code in the python scrapper.

**Comment by KarellenX** [comment]
Seems to scrape ok for me, both Human Resources (2022) and Project Runway...

![screenshot00001](https://github.com/thetvdb/metadata.tvshows.thetvdb.com.v4.python/assets/44626605/7d746d82-6d46-418c-9f7c-87470b73baf1)

**Comment by Nopel2020** [comment]
Hi,

I just tried rescraping the episodes (again...) and now all the info came through fine. Nothing changed on my end, not sure why it works now, but this issue can be closed.

Thanks for your help!

**Comment by antheaezzell** [comment]
Reopening this ticket @KarellenX I assume this is the right thread for Kodi re: this issue? https://forum.kodi.tv/showthread.php?tid=373710

**Comment by antheaezzell** [comment]
Internal ticket here: https://whipmedia.atlassian.net/browse/TVD-3800

**Comment by KarellenX** [comment]
Yep, that is the correct thread. In post # 3 he mentions the TBA issue.
I am pretty sure there was  a second report. I'll hunt around for it and post the link if I find it.

**Comment by HitcherUK** [comment]
I've been getting the same behaviour for the last 2 weeks, it seems to have started around 6 July.
No plot is getting scraped and only some episode titles, the rest are TBA.

**Comment by antheaezzell** [comment]
Added to ticket @HitcherUK thanks for the detail.

**Comment by HitcherUK** [comment]
Issue is fixed for me. All titles and plots are being scraped when I run a refresh information on the affected show.

Thanks.

**Comment by antheaezzell** [comment]
It's been internally tested too. I'm going to close this ticket out, but feel free to reopen if you see it again. @KarellenX FYI.
