### ISSUE TITLE
displayseason and displayepisode issues on special episodes

### ISSUE THREAD

**Issue by antheaezzell** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#4]
A Kodi user is running Kodi 19.3 (20211024-49a04cd6a7) on macOS Monterey 12.1

The scraper plugin is marked up as 'TheTVDB (new)' version 1.0.3 by Team Kodi. 

Issue #1: 

The TV show [Doctor Who (2005)](https://thetvdb.com/series/doctor-who-2005), and all of the specials have returned mixed up season/episode values for and so they appear in the wrong places in my library.

Ex: [S00E102 Tonight's the Night](https://thetvdb.com/series/doctor-who-2005/episodes/4760042) 

The episode should appear before the first episode of season 5, so should have 51. But it returns 15 so it appears before episode 5 in season 1.

Issue #2: 

If the episode number is higher than the maximum season number (there are 13 seasons of this show) the displayseason value is changed to 10000

Ex: [S00100 The Inforarium](https://thetvdb.com/series/doctor-who-2005/episodes/4750372)

The episode should appear after the last episode (13) of season 7 so should have 714. But it returns 100007 so it does not appear in sequence in the library at all.

User first noticed this issue 30 Jan 2022, and retried the process multiple times to no avail. Exported .nfo files that correspond to the two examples above are attached here:

S00E100 The Inforarium.1280x720.H264.AAC.2ch(1).nfo
15 Mar 2022, 03:15 PM
S00E102 Tonight's the Night.1280x720.H264.AAC.2ch.nfo
15 Mar 2022, 03:15 PM

User’s workaround has been to export the .nfo files for the episodes and manually correct the values, then refresh the metadata in her library. But that has proved to be quite laborious and time-consuming.

Also attaching a screenshot of the plugin and a log file of a scrape against the plugin for the first file mentioned (S00E102 Tonight's the Night). It asks if she wants to use the local information, but she chose to refresh against the internet to generate the log: 

Thanks!! 

osTicket reference
[kodi (1).log](https://github.com/thetvdb/metadata.tvshows.thetvdb.com.v4.python/files/8310052/kodi.1.log)
![Screenshot 2022-02-08 at 14 51 26 (1)](https://user-images.githubusercontent.com/80432059/159137406-fcd12217-29fa-4b8a-82b6-975f4476956d.png)
:

**Comment by antheaezzell** [comment]
See Jira ticket for internal reference - https://mediamorph.atlassian.net/browse/TVD-2886 and osTicket - https://support.thetvdb.com/scp/tickets.php?id=10753

**Comment by KarellenX** [comment]
Hi @antheaezzell 

Are you aware that is not your scraper? You may have confused the scrapers.

Your scraper appears in Kodi as TVDB v4. 
TVDB (new) is a python scraper created by razee just before your original announcement of deprecating API v1-3. None of the original TVDB scrapers have been maintained, in anticipation of the closure and your new scraper being released.

![tvdbv4](https://user-images.githubusercontent.com/44626605/159142343-b26b5fa9-4d48-42f7-bbca-d0903c9513b9.jpg)

**Comment by antheaezzell** [comment]
Thanks for the heads up @KarellenX I will inform this user that we can't be of help on this particular issue related to this scraper and close this issue.

**Comment by KarellenX** [comment]
Great. I guess what will happen is the user will contact our forum and all I can do is advise the scraper is unmaintained. 
Maybe ask them to install your new scraper to check the issue is solved?
