### ISSUE TITLE
Unable to scrape latest season of kitchen nightmares.

### ISSUE THREAD

**Issue by o0Saint0o** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#40]
I have tried removing the whole show from kodi , renaming from 'kitchen nightmares' to 'kitchen nightmares (US) and readding it a few times, ran the full debug log and for some reason it gets to the latest season which is 7 and then says it cannot find a match for that show.

https://thetvdb.com/series/kitchen-nightmares-us/seasons/official/7

Here is a small part of the scan, shows season 6 np but gets to 7 and just leaves the folder blank in kodi.

> 2023-10-22 23:05:10.226 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: performing getepisodelist action
> 2023-10-22 23:05:10.226 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: Getting episode list for show id 11294
> 2023-10-22 23:05:10.227 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: using cached show info
> 2023-10-22 23:05:10.227 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S1E1 - Peter's to list item
> 2023-10-22 23:05:10.227 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S1E2 - Dillon's to list item
> 2023-10-22 23:05:10.227 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S1E3 - The Mixing Bowl to list item
> ===== removed ======
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E2 - Pantaleone's to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E3 - Old Neighborhood to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E4 - Kati Allo to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E5 - Mangia Mangia, Pt 1 to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E6 - Mangia Mangia, Pt 2 to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E7 - Zayna Flaming Grill, Pt 1 to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E8 - Zayna Flaming Grill, Pt 2 to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E9 - Bella Luna to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: adding episode information for S6E10 - Revisited to list item
> 2023-10-22 23:05:10.231 T:29336   debug <general>: CPythonInvoker(1, C:\Users\jtrev\AppData\Roaming\Kodi\addons\metadata.tvshows.themoviedb.org.python\main.py): script successfully run
> 2023-10-22 23:05:10.232 T:23012   debug <general>: VIDEO::CVideoInfoScanner::OnProcessSeriesFolder - no match for show: 'Kitchen Nightmares', season: 7, episode: 1.0, airdate: '01/01/1601', title: '' 
> 2023-10-22 23:05:10.287 T:23012   debug <general>: VIDEO::CVideoInfoScanner::OnProcessSeriesFolder - no match for show: 'Kitchen Nightmares', season: 7, episode: 2.0, airdate: '01/01/1601', title: ''
> 2023-10-22 23:05:10.294 T:23012   debug <general>: VIDEO::CVideoInfoScanner::OnProcessSeriesFolder - no match for show: 'Kitchen Nightmares', season: 7, episode: 3.0, airdate: '01/01/1601', title: ''
> 2023-10-22 23:05:10.335 T:23012   debug <general>: VIDEO::CVideoInfoScanner::OnProcessSeriesFolder - no match for show: 'Kitchen Nightmares', season: 7, episode: 4.0, airdate: '01/01/1601', title: ''
>

**Comment by KarellenX** [comment]
You have provided the link to **TVDB** site, yet you are using the **themoviedb** scraper?
What does themoviedb show?

**Comment by o0Saint0o** [comment]
yea stupid me, thanks for pointing that out. somewhere down the line my library switched from TVDB4 scraper to the Tmdb TV one. I've re-scraped the entire library and all looks good now.

**Comment by KarellenX** [comment]
>I've re-scraped the entire library with the TVDB v4 and all looks good now.

Great that it's all working now :)
