### ISSUE TITLE
nfo file parsing

### ISSUE THREAD

**Issue by sergserg2** [thetvdb/metadata.tvshows.thetvdb.com.v4.python#5]
Use of 'www.thetvdb.com' address in nfo file raises HTTP error (lack of numeric id in request to API).

Modification of the regex that solves the problem (nfo.py)
`SERIES_URL_REGEX = re.compile(r'https?://[w\.]*thetvdb.com/series/([\w-]+)', re.I)`

**Comment by KarellenX** [comment]
Is your fix related to this issue... https://github.com/xbmc/xbmc/issues/19845

**Comment by sergserg2** [comment]
> Is your fix related to this issue... [xbmc/xbmc#19845](https://github.com/xbmc/xbmc/issues/19845)

No.
